Upgrade dev deps and misc changes to support PHP 8.2-8.4, drop PHP 7.3
== Upgrade ==

* Switch GitHub workflow to ppa:ondrej/php and add PHP 8.4
  Ref https://github.com/actions/runner-images/issues/6331
  Ref https://github.com/wikimedia/less.php/issues/117

* Upgrade phan to fix crash on PHP 8.4
  ```
  PHP Deprecated: Constant ASSERT_ACTIVE is deprecated
    in /vendor/phan/phan/src/Phan/Bootstrap.php
  PHP Deprecated: Function assert_options() is deprecated
    in /vendor/phan/phan/src/Phan/Bootstrap.php
  PHP Deprecated: Implicitly marking parameter $suggestion as nullable is deprecated
    in /vendor/phan/phan/src/Phan/Issue.php Phan\Issue::__invoke():
  ERROR: Error: Class "Phan\Issue" not found
    in /stillalive/vendor/phan/phan/src/Phan/Config.php:366
    at stillalive/vendor/bin/phan:119
  Script phan … returned with error code 1
  ```

* Silence new PHan rules that we don't (yet) meet:

  - MediaWikiNoBaseException
    at src/FileCacheStore.php:16 Instantiating \Exception directly is not allowed. See https://w.wiki/6nur

== Fixed ==

Fixed issues in the error log when serving over PHP 8.4 and/or
caught by unit tests.

```
PHP Deprecated: Creation of dynamic property MemoryCacheStoreTest::$cache is deprecated
  in /test/unit/suites/MemoryCacheBackendTest.php on line 8

PHP Deprecated: Krinkle\Toolbase\LabsDB::query():
  Implicitly marking parameter $bindings as nullable is deprecated
  in /src/LabsDB.php on line 169

PHP Deprecated: Wikimedia\ScopedCallback::consume():
  Implicitly marking parameter $sc as nullable is deprecated
  in /vendor/wikimedia/scoped-callback/src/ScopedCallback.php on line 55

  Fixed by upgrading wikimedia/scoped-callback.
  Ref https://gerrit.wikimedia.org/r/c/mediawiki/libs/ScopedCallback/+/1081235

PHP Deprecated:  Krinkle\Toolbase\HtmlSelect::addOption():
  Implicitly marking parameter $text as nullable is deprecated,
  in /src/HtmlSelect.php on line 3

PhanUnusedGlobalFunctionParameter
  Parameter $precision is never used in src/GlobalFunctions.php:274

PhanUnusedPublicNoOverrideMethodParameter
  Parameter $default is never used in src/Request.php:58

MediaWikiNoIssetIfDefined
  Found usage of isset() on expression self::$dbInfos
```